language: python
python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python manage.py test apps

notifications:
  email:
    - marcresaenrich@gmail.com
    - aguilars99@gmail.com
    - guillem.escarp@gmail.com
    - xtrullols35@gmail.com