version: "3"

services:
  web:
    build: .
    command: python manage.py runserver
    container_name: Twitter_
    env_file:
    - .env
    ports:
    - "8000:8000"
    depends_on:
    - db
    volumes:
    - .:/code
  db:
    image: postgres
    
    
}