# Generated by Django 3.0.4 on 2020-03-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='id',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='hashtag',
            field=models.TextField(default='', max_length=279, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='impact',
            name='id_tweet',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet'),
        ),
        migrations.AddField(
            model_name='impact',
            name='stat_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impact',
            name='type_stat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='twitter.Statistics'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='type_stat',
            field=models.CharField(default='', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtag_in_tweet',
            field=models.ManyToManyField(related_name='hashtags_tweet', to='twitter.Hashtag'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='id_tweet',
            field=models.PositiveIntegerField(default=123, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(default='', help_text='280 characters max', max_length=280),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='tweet',
            field=models.ManyToManyField(related_name='personal_tweets', to='twitter.Tweet'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='username',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
