# Generated by Django 3.0.4 on 2020-03-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impact',
            old_name='type_stat',
            new_name='stat',
        ),
        migrations.RenameField(
            model_name='impact',
            old_name='id_tweet',
            new_name='tweet',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='numtweets',
        ),
    ]
